apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - env:
            - name: BACKEND_CORS_ORIGINS
              value: '["http://localhost:3000", "http://localhost:5000", "https://evox.rasztabiga.me"]'
            - name: POSTGRES_SERVER
              value: db
            - name: POSTGRES_USER
              value: evox
            - name: POSTGRES_PASSWORD
              value: evox
            - name: POSTGRES_DB
              value: evox
            - name: API_KEY
              value: ca9c1d4509ec6c9b9550fecfab3817a9b87e5e06bcbfe94298b12ce14ca8e428
          image: navareth/evox:sha-25197a1
          name: backend
          ports:
            - containerPort: 8080
      restartPolicy: Always
