"""Initial schema (Message)

Revision ID: 17e84c52321f
Revises: 
Create Date: 2021-05-22 12:31:43.408142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '17e84c52321f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(length=160), nullable=False),
                    sa.Column('views_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
