name: Backend

on:
  push:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Poetry
        run: |
          pip install poetry
          poetry install -v
      - name: Lint
        run: |
          poetry run ./scripts/lint.sh

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: evox
          POSTGRES_PASSWORD: evox
          POSTGRES_DB: evox
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        run: |
          pip install poetry
          poetry install -v
      - name: Test
        run: |
          poetry run bash ./prestart.sh
          poetry run pytest --cov=app --cov-report=xml app/tests "${@}"
